# Generated by Django 5.2.5 on 2025-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cihazlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihaz',
            name='kaynak_dosya',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
