# Generated by Django 5.2.5 on 2025-08-25 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cihazlar', '0002_cihaz_kaynak_dosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihaz',
            name='eklenme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cihaz',
            name='son_degistirilme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cihaz',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
