# Generated by Django 5.2.5 on 2025-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cihazlar', '0003_cihaz_eklenme_tarihi_cihaz_son_degistirilme_tarihi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cihaz',
            old_name='son_degistirilme_tarihi',
            new_name='son_degistirilme',
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='eklenme_tarihi',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='kaynak_dosya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='test_durumu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
